version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run generate
  post_build:
    commands:
      - aws s3 sync dist s3://philippe-website --delete
artifacts:
  # IMPORTANT - Please verify your build output directory
  baseDirectory: dist/
  files:
    - "**/*"
cache:
  paths:
    - node_modules/**/*
